# -*- coding: utf-8 -*-
"""SISTEMA DE VENDAS: PIZZARIA DA DAIANA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tHIy4rqY4gwKqUM5BTlSpDOwkwfklMYA
"""

print('--- SISTEMA DE VENDAS: PIZZARIA DA DAIANA ---')
# Aqui entra a parte do RH: Identificação da equipe
atendente = input('Informe o nome do colaborador(a) que está operando o sistema: ')

print(f'\nOlá, {atendente}! Vamos iniciar um novo atendimento.')
cliente = input('Qual o nome do cliente? ')

print(f'\nBem-vindo(a), {cliente}! Confira nosso cardápio:')
print('-' * 45)
print('Tamanho | Pizza Salgada (PS) | Pizza Doce (PD)')
print('P       | R$ 30.00           | R$ 34.00')
print('M       | R$ 45.00           | R$ 48.00')
print('G       | R$ 60.00           | R$ 66.00')
print('-' * 45)

total_pedidos = 0.0
itens_pedidos = [] # Lista para guardar o que foi pedido

while True:
    sabor = input('\nSabor (PS/PD): ').upper().strip()
    if sabor not in ['PS', 'PD']:
        print('Sabor inválido. Tente novamente.')
        continue

    tamanho = input('Tamanho (P/M/G): ').upper().strip()
    if tamanho not in ['P', 'M', 'G']:
        print('Tamanho inválido. Tente novamente.')
        continue

    # Lógica de preços
    if sabor == 'PS':
        nome_sabor = "Salgada"
        precos = {'P': 30.0, 'M': 45.0, 'G': 60.0}
    else:
        nome_sabor = "Doce"
        precos = {'P': 34.0, 'M': 48.0, 'G': 66.0}

    valor = precos[tamanho]
    total_pedidos += valor

    # Guarda o item para o comprovante final
    itens_pedidos.append(f"1x Pizza {nome_sabor} ({tamanho}) - R${valor:.2f}")
    print(f'>> Adicionado: Pizza {nome_sabor} {tamanho}')

    prosseguir = input('Deseja adicionar mais itens? (S/N): ').upper().strip()
    if prosseguir == 'N':
        break

# --- COMPROVANTE FINAL ---
print('\n' + '='*40)
print(f'       RESUMO DO PEDIDO - PIZZARIA DA DAIANA')
print('='*40)
print(f'Cliente: {cliente}')
print(f'Atendente: {atendente}')
print('-' * 40)
for item in itens_pedidos:
    print(item)
print('-' * 40)
print(f'TOTAL A PAGAR: R${total_pedidos:.2f}')
print('='*40)
print(f'Obrigada pela preferência, {cliente}!')
print(f'Tenha um excelente trabalho, {atendente}!')